### ISSUE TITLE
The cell width should be calculated using the data when applying a `formatter`

### ISSUE THREAD

**Issue by koffeinfrei** [hutou/tablo#2]
The documentation

> formatter: a Proc to format the cells, while conserving the inferred alignment from the body contents. Default to "->(n : CellType) { n.to_s }"

suggests that the value from the `fomatter` does not influence the calculation / alignment of the cell.

When using a formatter to output the value with a color (using Crystal's `Colorize`) the cell width is not calculated based on the data value, but based on the value provided by the `formatter`.

```ruby
Tablo::Table.new(table_data, connectors: Tablo::CONNECTORS_SINGLE_ROUNDED) do |t|
  t.add_column("Diff", width: COLUMN_WIDTH, formatter: ->(n : Tablo::CellType) { n.colorize(:red).to_s }) { |n| n[1] }
end
```

Expected output:
![image](https://user-images.githubusercontent.com/176582/143625046-3a99aa9a-4bf7-4e39-a792-4b05c6920a08.png)

Actual output:
![image](https://user-images.githubusercontent.com/176582/143624999-710b2e8d-65e6-44d6-bac9-31e013f79a82.png)

[Tabulo](https://github.com/matt-harvey/tabulo#colours-and-other-styling-) also mentions this:

> In most terminals, if you want to print text that is coloured, or has certain other styles such as underlining, you need to use ANSI escape sequences, either directly, or by means of a library such as Rainbow that uses them internally. Tabulo needs to properly account for escape sequences when performing the width calculations required to render tables. The styler option on the add_column method is intended to facilitate this.

Is this the intended behaviour for tablo as well? If so [the width calculation](https://github.com/hutou/tablo/blob/master/src/column.cr#L54) should be based on the data value instead of the formatted value.

**Comment by matt-harvey** [comment]
Hi @koffeinfrei , author of [Tabulo](https://github.com/matt-harvey/tabulo) here.

Just to clarify, **Tabulo** has two distinct concepts in this space: the [formatter](https://github.com/matt-harvey/tabulo#formatting-cell-values-); and the [styler](https://github.com/matt-harvey/tabulo#styling-cell-content-). These are configurable as distinct options when initializing a table column.

The formatter's output _is_ taken into account for the width calculations. For example, a formatter for displaying dollar amounts might turn an integer `1` into a string `$1.00`, and then the table's internals must take the width of that string into account when rendering the table.

From what I can see, this behaviour around the formatter option is the same in Tablo.

> while conserving the inferred alignment from the body contents

I gather this is also the same as in Tabulo, where numbers are right-aligned by default, and strings are left-aligned by default, and the formatter option doesn't affect whether something is regarded as a number or a string _for the purpose of determining its default left/right/centre alignment_. I believe that's what this documentation comment is referring to&mdash;only that.

Let's now consider the case where one wants to make that string `$1.00` appear red in the terminal. In Tabulo, one would then use the `styler` option to do so; and any additional control characters in the styler's output, would _not_ be taken into account for the width calculations. This enables colours etc. to be applied without breaking the rendered table layout.

Prior to [v1.5.0](https://github.com/matt-harvey/tabulo/blob/master/CHANGELOG.md#v150), Tabulo did not have a distinct styler option, meaning that it was not possible to apply ANSI sequences to render colours etc. without breaking the width calculations and hence the table layout. The point of `styler` is to provide a mechanism to manipulate these styles without breaking the formatting, hence addressing the issue you've raised here.

As far as I can see, **Tablo** does not have a similar "styler" mechanism; though perhaps I am wrong, as I am not too familiar with this library.

**Comment by koffeinfrei** [comment]
:wave: @matt-harvey Thanks for your thorough explanation!
So yes basically tablo is missing the `styler` concept. @hutou Is this something we could add? Are there other plans? Or should the expected behaviour deviate from tabulo?
In the end my use case is to have colored output. If there are any other ways to achive this please let me know.

**Comment by hutou** [comment]
Hi,
Tablo is an adaptation of tabulo to the Crystal language made almost 3 years ago, and has not evolved much since then. I made this adaptation while learning Crystal and there is more than likely a lot of room for improvement to make Tablo as flexible as Tabulo.

So, in its current version, Tablo does not have a style option. This feature is definitely very useful and I think that when I find time to work on the Tablo project again, I will put it on the top of the 'to do' pile!

In the meantime, if necessary, it is always possible to work around the missing style option by using a trick, such as the (ugly, but working) code below:
```
require "tablo"
require "colorize"

data = [
  [1, 2, 3],
  [-4, 5, 6],
  [7, -8, -9],
]

table = Tablo::Table.new(data) do |t|
  t.add_column("Col1") { |n| n[0] }
  t.add_column("Col2") { |n| n[1] }
  t.add_column("Col3") { |n| n[2] }
end

table.each do |row|
  cols = row.to_s.split("|")
  r = cols.map_with_index { |c, i|
    c =~ /-\d+/ && i == 2 ? c.colorize(:red) : c
  }.join("|")
  puts r
end
puts table.horizontal_rule(Tablo::TLine::Bot)
```
![test_cr](https://user-images.githubusercontent.com/5678331/143693129-540b58cf-5cf6-4ed1-bfbe-28b803e7e3ea.png)

**Comment by koffeinfrei** [comment]
@hutou I had a quick go at the feature in the meantime: https://github.com/hutou/tablo/pull/3. Let me know what you think.
